version: '3.3'
services:
  documentacao:  
    container_name: documentacao
    image: documentacao
    build: 
      context: .
      dockerfile: Dockerfile
        #    command: npm install -g docsify-cli 
    entrypoint: ["docsify", "serve", "/app/docs"]
    volumes:
      - ./docs:/app/docs
    ports: 
      - "3000:3000"
